# Generated by Django 4.2.2 on 2023-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_invoice', models.IntegerField(default=1)),
                ('nome_emissor', models.CharField(max_length=100)),
                ('sobrenome_emissor', models.CharField(max_length=100)),
                ('email_emissor', models.CharField(max_length=50)),
                ('cnpj_emissor', models.CharField(max_length=100)),
                ('swiftcode', models.CharField(max_length=100)),
                ('ibancode', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=100)),
                ('cep_emissor', models.CharField(max_length=10)),
                ('logradouro_emissor', models.CharField(max_length=100)),
                ('complemento_emissor', models.CharField(max_length=100)),
                ('num_emissor', models.CharField(max_length=5)),
                ('bairro_emissor', models.CharField(max_length=50)),
                ('cidade_emissor', models.CharField(max_length=50)),
                ('estado_emissor', models.CharField(max_length=50)),
                ('nome_destinatario', models.CharField(max_length=100)),
                ('cnpj_destinatario', models.CharField(max_length=100)),
                ('cep_destinatario', models.CharField(max_length=10)),
                ('logradouro_destinatario', models.CharField(max_length=100)),
                ('num_destinatario', models.CharField(max_length=5)),
                ('bairro_destinatario', models.CharField(max_length=50)),
                ('cidade_destinatario', models.CharField(max_length=50)),
                ('estado_destinatario', models.CharField(max_length=50)),
                ('issuedate', models.DateField()),
                ('duedate', models.DateField()),
            ],
        ),
    ]
