# Generated by Django 4.2.2 on 2023-06-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='username',
            field=models.CharField(default='eliascastro', max_length=100),
            preserve_default=False,
        ),
    ]
