# Generated by Django 4.2.2 on 2023-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cnpj',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='ibancode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='salario',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='swiftcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
