# Generated by Django 4.2.2 on 2023-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_endereco_cnpj_endereco_ibancode_endereco_salario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='salario',
            field=models.CharField(max_length=10),
        ),
    ]
